#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

IDF_PATH := $(shell pwd)/../ESP8266_RTOS_SDK-3.0
export IDF_PATH

PROJECT_NAME := esp_firmware

include $(IDF_PATH)/make/project.mk
